FROM  golang:1.10
LABEL maintainer="Dũng Đặng Minh <dungdm93@gmail.com>"

RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

####### INSTRUCTIONS #######
# Build image:
# $ docker build -t dungdm93/golang-dev:1.10-debian .
# Run image:
# $ docker run -it --rm --name golang-dev dungdm93/golang-dev:1.10-debian bash
############################
